# Generated by Django 5.0.14 on 2026-08-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_screening', '0002_remove_candidatecv_candidate_name_and_more'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='screening_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='cv_screening.rolekeywordprofile'),
        ),
    ]
