# Generated by Django 5.0.14 on 2026-08-17 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_screening', '0002_remove_candidatecv_candidate_name_and_more'),
        ('positions', '0002_position_screening_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='screening_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_screening.rolekeywordprofile'),
        ),
    ]
