# Generated by Django 5.0.14 on 2026-09-18 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_deactivated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='chiefs',
            field=models.ManyToManyField(blank=True, related_name='chief_of_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
