# Generated by Django 5.0.14 on 2026-08-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateCV',
        ),
    ]
