# Generated by Django 5.0.14 on 2026-08-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_delete_candidatecv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('CV Screening', 'CV Screening'), ('CV Screening Passed', 'CV Screening Passed'), ('CV Screening Failed', 'CV Screening Failed'), ('HR Interview', 'HR Interview'), ('Technical Interview', 'Technical Interview'), ('Senior Review', 'Senior Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=30),
        ),
    ]
