# Generated by Django 5.0.14 on 2026-09-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_user_alter_application_status_and_more'),
        ('positions', '0003_alter_position_screening_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('staff', 'Added by staff'), ('public', 'Applied online')], default='staff', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PendingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='pending_cvs/')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_applications', to='positions.position')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
