# Generated by Django 5.0.14 on 2026-09-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_source_candidate_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_message',
            field=models.TextField(blank=True),
        ),
    ]
