#!/usr/bin/env bash
#
# Regenerate the collected static files after a configuration change.
#
# A configuration update re-extracts the application source but does not run
# the .ebextensions container commands. The staticfiles/ directory is
# generated by collectstatic and is not in the bundle, so it disappears --
# and under manifest storage every {% static %} lookup then raises, which
# takes the entire site to HTTP 500. That is exactly what happened when
# CLOUDFRONT_ORIGIN_SECRET was added on 2026-09-20.
#
# Deliberately never fails the configuration update: if this cannot run, the
# result is the same 500 as before, and blocking every future config change
# would be worse.

set -uo pipefail

LOG=/var/log/candidflow-confighook.log
exec >>"$LOG" 2>&1
echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] collectstatic after config change"

# The startup guards refuse to load settings without SECRET_KEY and
# DJANGO_ALLOWED_HOSTS, and a hook does not inherit the environment
# properties, so read them the same way the housekeeping jobs do.
for candidate in /opt/elasticbeanstalk/deployment/env /opt/elasticbeanstalk/deployment/candidflow_env; do
    if [ -r "$candidate" ]; then
        while IFS='=' read -r key value || [ -n "$key" ]; do
            case "$key" in ''|'#'*) continue ;; esac
            export "$key=$value"
        done <"$candidate"
        break
    fi
done

app_dir=/var/app/staging
[ -f "$app_dir/manage.py" ] || app_dir=/var/app/current

venv=$(echo /var/app/venv/*/bin/activate)
if [ ! -r "$venv" ]; then
    echo "  no virtualenv found; skipping"
    exit 0
fi

# shellcheck disable=SC1090
source "$venv"
cd "$app_dir" || exit 0

python manage.py collectstatic --noinput
echo "  finished with status $?"

exit 0
