# Generated by Django 5.0.14 on 2026-07-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='cvs/')),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleKeywordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=150)),
                ('nice_to_have_skills', models.ManyToManyField(blank=True, related_name='nice_to_have_for_roles', to='cv_screening.skill')),
                ('required_skills', models.ManyToManyField(related_name='required_for_roles', to='cv_screening.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='cv_screening.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CVMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='cv_screening.candidatecv')),
                ('role_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_screening.rolekeywordprofile')),
                ('matched_nice_to_have', models.ManyToManyField(blank=True, related_name='matched_nice_to_have_in', to='cv_screening.skill')),
                ('matched_required', models.ManyToManyField(blank=True, related_name='matched_required_in', to='cv_screening.skill')),
                ('missing_required', models.ManyToManyField(blank=True, related_name='missing_required_in', to='cv_screening.skill')),
            ],
            options={
                'unique_together': {('cv', 'role_profile')},
            },
        ),
    ]
