# Generated by Django 5.0.14 on 2026-08-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_delete_candidatecv'),
        ('cv_screening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatecv',
            name='candidate_name',
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screening_cvs', to='candidates.candidate'),
        ),
    ]
