# Generated by Django 5.0.14 on 2026-09-15 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interviews.interviewfeedback'),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='interviews.interview'),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Hold', 'Hold'), ('Reject', 'Reject')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='FeedbackAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('diff', models.JSONField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='interviews.interviewfeedback')),
            ],
        ),
    ]
