# Generated by Django 5.0.14 on 2026-09-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewfeedback_author_interviewfeedback_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackauditlog',
            name='action',
            field=models.CharField(choices=[('EDITED', 'EDITED'), ('DELETED', 'DELETED')], default='EDITED', max_length=10),
        ),
        migrations.AddField(
            model_name='feedbackauditlog',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interviews.interview'),
        ),
        migrations.AlterField(
            model_name='feedbackauditlog',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='interviews.interviewfeedback'),
        ),
    ]
